### PR TITLE
Add new allowed file formats - JPEG and PNG

### PR DESCRIPTION
**Pull request by CrystalPea**
For JPEG, I had to choose between .jpg and .jpeg file extension, as they share the same mimetype, and we use mimetypes as keys in our ALLOWED_FILE_TYPES dict. I chose .jpeg, since .jpg is a legacy extension stemming from DOS system's restriction on number of characters in an extension 30 years ago - so with time it should be used less and less.

---

🚨⚠️ This will be deployed automatically all the way to production when you click merge ⚠️🚨

For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on deployment](https://github.com/alphagov/notifications-manuals/wiki/Merging-and-deploying#deployment)

### CODE REVIEW

**Review by quis — COMMENTED** [review]
If we flipped the `ALLOWED_FILE_TYPES` from `{mime_type: extension}` to `{extension: mime_type}` then we could support both `jpeg` and `jpg`

**Comment by CrystalPea** [comment]
@quis true, only then we would have trouble with `.rtf`, which has two mimetypes 😅  (I tried it when I was writing this code, and run into that conundrum 😳 - actually it was flipped the other way, and then a few years ago Ben flipped it to what it is 😆 )

**Comment by quis** [comment]
In that case something like this would cover both:

```python
ALLOWED_FILE_TYPES = (
    ("jpg", "image/jpeg"),
    ("jpeg", "image/jpeg"),
    ("rtf", "text/rtf"),
    ("rtf", "application/rtf"),
)

FILE_EXTENSION_TO_MIME_TYPE = dict(ALLOWED_FILE_TYPES)
MIME_TYPE_TO_FILE_EXTENSION = {v: k for k, v in ALLOWED_FILE_TYPES.items()}
```

**Comment by CrystalPea** [comment]
@quis but then we couldn't find the values by key, like we do here for example: https://github.com/alphagov/document-download-api/blob/c4ec475cfca52fb7166f0de4618a63bd9fdc4951/app/download/views.py#L90

We need one side at least to be unique, I think.

Do you think it's a big problem to only allow .jpeg, but not .jpg? The users who need to send pictures can always change the extension, no?

**Comment by quis** [comment]
Using the sample I gave above:
```python
FILE_EXTENSION_TO_MIME_TYPE["jpg"]
>>> "image/jpeg"

MIME_TYPE_TO_FILE_EXTENSION["image/jpeg"]
>>> "jpeg"
```
(it will default to whichever key was defined furthest down in the list)

Accepting both feels like a good example of the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) (“be conservative in what you send, be liberal in what you accept”)

**Comment by CrystalPea** [comment]
@quis makes sense, I will do it like you proposed then, thanks. Since our code will depend on the order of the items in the tuple of tuples now, I will add a comment about this, and an extra test, and I will let you know when I'm finished.

**Review by quis — APPROVED** [review]

**Pull request merged**
